project:
  type: website

  render:
    - "index.qmd"
    - "src/introduction/index.qmd"
    - "src/principles/index.qmd"
    - "src/implementation/index.qmd"
    - "src/mlops/index.qmd"
    - "src/discussion/index.qmd"

website: 
  page-navigation: true
  site-url: "https://inseefrlab.github.io/DT-cloud-prod-stat/fr/" 
  repo-url: "https://github.com/InseeFrLab/DT-cloud-prod-stat"
  # repo-actions: [edit, source, issue]
  favicon: images/favicon.ico

  sidebar:
    style: "docked"
    background: "light"
    
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: translate
        menu: 
          - href: ../fr/
            text: "Français"
          - href: ../en/
            text: "English"

format:
  html:
    theme: cosmo
    css: styles/styles.css
    toc: true
    code-annotations: hover
    code-link: true
    reference-location: margin
    number-sections: true

bibliography: src/references.bib 
