project:
  type: website

  render:
    - "*.qmd"

website: 
  title: DT Cloud & Production Statistique
  page-navigation: true
  site-url: "https://inseefrlab.github.io/DT-cloud-prod-stat/"
  repo-url: "https://github.com/InseeFrLab/DT-cloud-prod-stat"
  favicon: images/favicon.ico

  sidebar:
    style: "docked"
    background: "light"
    favicon: images/favicon.ico
    pinned: true
    align: center
    contents:
      - text: "1 - Introduction"
        href: src/introduction/index.qmd
      - text: "2 - Principes"
        href: src/principles/index.qmd
      - text: "3 - Implémentation"
        href: src/implementation/index.qmd
      - text: "4 - MLOps"
        href: src/mlops/index.qmd
      - text: "5 - Discussion"
        href: src/discussion/index.qmd
    tools: 
      - icon: file-pdf-fill
        href: dt-cloud-prod-stat.pdf
        text: "PDF"

format:
  html:
    theme: cosmo
    css: styles/styles.css
    toc: true
    code-annotations: hover
    code-link: true
    reference-location: margin
    number-sections: true

bibliography: src/references.bib 
